# Generated by Django 5.1.3 on 2024-11-24 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="taskpriority",
            name="slug",
            field=models.SlugField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name="taskstatus",
            name="slug",
            field=models.SlugField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="task", name="title", field=models.CharField(unique=True),
        ),
        migrations.AlterField(
            model_name="taskpriority", name="name", field=models.CharField(unique=True),
        ),
        migrations.AlterField(
            model_name="taskstatus", name="name", field=models.CharField(unique=True),
        ),
    ]
