# Generated by Django 5.1.3 on 2024-11-24 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0002_taskpriority_slug_taskstatus_slug_alter_task_title_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="slug",
            field=models.SlugField(null=True, unique=True),
        ),
    ]
