# Generated by Django 5.1.3 on 2024-11-24 21:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0003_task_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="status",
            field=models.ForeignKey(
                default="In Progress",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="tasks.taskstatus",
            ),
        ),
    ]
